# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='id',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='skuid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
